### ISSUE TITLE
Values could not be parsed to Float64

### ISSUE THREAD

**Issue by pete-leese** [tolleiv/json-exporter#3]
I have set this up but struggling to get it return any data from my feed.

console output states the following:

2018/03/12 11:39:10 Found value 17.8

but when hitting the URL it just displays:

Values could not be parsed to Float64

The json I am trying to query is as follows:
{  
   "isValid":true,
   "validationRuleErrors":[],
   "httpStatusCode":200,
   "genericErrorMessage":null,
   "data":{  
      "version":"17.8"
   }
}

I am able to read httpStatusCode OK, however for other values such as isValid etc... this throws the same error. 

Example query:

http://XXXX:9116/probe?target=http://XXXX.com/api/version/?json=%7B%22key%22:%22value%22&jsonpath=$.data.version

Secondly, is there a way to change the  metric label from just outputting "value" to give each of the above json keys a unique identifier.

Any ideas ?

**Comment by SPFZ** [comment]
To your second question, you can use this in your scrape config to overwrite the metric name (which is just a hidden label called \_\_name\_\_):

```

metric_relabel_configs:
      - source_labels: [__name__]
        regex: value
        target_label: __name__
        replacement: custom_metric_name
```
This overwrites "value" with "custom_metric_name".
